CREATE DATABASE IF NOT EXISTS whale;

CREATE TABLE IF NOT EXISTS whale.COMPANY(
	id 				BIGINT AUTO_INCREMENT PRIMARY KEY,
	法人单位名称 		VARCHAR(100),
	注册资金 			DOUBLE,
	注册时间 			DATETIME,
	资产总计 			VARCHAR(100),
	主营业务收入 		DOUBLE,
	人员规模 			BIGINT,
	主营行业 			VARCHAR(100),
	地址 				VARCHAR(100),
	邮政编码 			VARCHAR(100),
	区号				VARCHAR(100),
	电话号码			VARCHAR(100),
	分机号				VARCHAR(100),
	传真号码			VARCHAR(100),
	数据来源			VARCHAR(100),
	法定代表人			VARCHAR(100),
	法人性别			VARCHAR(100),
	法人身份证号			VARCHAR(100),
	法人手机号			VARCHAR(100),
	法人电子邮箱			VARCHAR(100),
	行政区划代码			VARCHAR(100),
	营业状态			VARCHAR(100),
	执行会计制度类别 		VARCHAR(100),
	机构类型			VARCHAR(100),
	网址				VARCHAR(100),
	行业代码			VARCHAR(100),
	控股情况			VARCHAR(100),
	隶属关系			VARCHAR(100),
	导入时间			TIMESTAMP,
	联系人姓名			VARCHAR(100),
	联系人性别			VARCHAR(100),
	证件名称			VARCHAR(100),
	联系人身份证号码		VARCHAR(100),
	联系人手机号			VARCHAR(100),
	联系人电子邮箱		VARCHAR(100),
	联系人所在部门		VARCHAR(100),
	联系人职务			VARCHAR(100),
	联系人毕业时间		DATETIME,
	联系人毕业学校		VARCHAR(100),
	联系人专业			VARCHAR(100),
	联系人最高学历		VARCHAR(100),			
 	活动方式			VARCHAR(100),
 	参加日期			DATETIME,
 	活动项目名称			VARCHAR(100),
	备注1				VARCHAR(200),
	备注2 			VARCHAR(200),
	备注3 			VARCHAR(200),
	备注4 			VARCHAR(200),
	备注5 			VARCHAR(200),
	UNIQUE INDEX `法人单位名称` (`法人单位名称`, `联系人手机号`)
)ENGINE=INNODB, DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS whale.PERSON(
	id 					BIGINT AUTO_INCREMENT PRIMARY KEY,
	姓名	 				VARCHAR(100),
	性别	 				VARCHAR(100),
	出生日期	 			DATETIME,
	联系电话	 			VARCHAR(100),
	手机号码	 			VARCHAR(100),
	行政区域	 			VARCHAR(100),
	地址		 			VARCHAR(100),
	邮编	 				VARCHAR(100),	
	用户级别	 			VARCHAR(100),	
	邮箱	 				VARCHAR(100),	
	年收入	 				DOUBLE,	
	毕业学校	 			VARCHAR(100),	
	最高学历	 			VARCHAR(100),	
	专业		 			VARCHAR(100),
	入网日期	 			VARCHAR(100),
	导入日期	 			TIMESTAMP,
	数据来源	 			VARCHAR(100),	
	社保账号	 			VARCHAR(100),	
	缴金基数	 			VARCHAR(100),	
	传真		 			VARCHAR(100),
	所属行政区域代码	 		VARCHAR(100),	
	登记住所	 			VARCHAR(100),	
	职务		 			VARCHAR(100),
	证件名称	 			VARCHAR(100),	
	证件号码	 			VARCHAR(100),	
	工作性质	 			VARCHAR(100),	
	所在单位	 			VARCHAR(100),	
	所属行业代码	 			VARCHAR(100),		
	用户状态	 			VARCHAR(100),
	车辆品牌	 			VARCHAR(100),	
	车价位		 			DOUBLE,
	厂牌型号	 			VARCHAR(100),	
	产品国别	 			VARCHAR(100),	
	使用性质	 			VARCHAR(100),	
	购车日期	 			DATETIME,	
	车牌		 			VARCHAR(100),
	出行方式	 			VARCHAR(100),	
	发动机号	 			VARCHAR(100),	
	燃油种类	 			VARCHAR(100),	
	车身颜色	 			VARCHAR(100),	
	检验有效日期	 			VARCHAR(100),	
	发证日期		 		VARCHAR(100),
	初次登记日期	 			VARCHAR(100),	
	车辆识别代码	 			VARCHAR(100),
	楼盘名称	 			VARCHAR(100),	
	楼号		 			VARCHAR(100),
	室号		 			VARCHAR(100),
	户型	 				VARCHAR(100),	
	面积		 			VARCHAR(100),
	终止日期	 			VARCHAR(100),	
	保险		 			VARCHAR(100),
	生效日期	 			VARCHAR(100),							
	发卡银行	 			VARCHAR(100),	
	卡名		 			VARCHAR(100),
	资金量（万）	 			VARCHAR(100),												
	运营商		 			VARCHAR(100),
	手机品牌	 			VARCHAR(100),													
	子女姓名		 		VARCHAR(100),
	子女性别	 			VARCHAR(100),	
	子女年龄	 			BIGINT,	
	子女所属校区		 		VARCHAR(100),
	子女就读年级	 			VARCHAR(100),	
	子女毕业时间	 			VARCHAR(100),	
	子女考试课程	 			VARCHAR(100),	
	子女分数		 		VARCHAR(100),
	子女手机号码	 			VARCHAR(100),						
	网店名称		 		VARCHAR(100),
	购买产品	 			VARCHAR(100),	
	交易日期	 			DATETIME,	
	交易金额	 			DOUBLE,	
	支付账户	 			VARCHAR(100),										
	活动方式		 		VARCHAR(100),
	参加日期		 		VARCHAR(100),
	活动项目名称	 			VARCHAR(100),
	备注1			VARCHAR(200), 	
	备注2			VARCHAR(200),	
	备注3			VARCHAR(200),	
	备注4 			VARCHAR(200),	
	备注5			VARCHAR(200),
	UNIQUE INDEX `姓名` (`姓名`, `手机号码`)
)ENGINE=INNODB, DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS whale.`user` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(100) NULL,
	`password` VARCHAR(100) NULL DEFAULT NULL,
	`issuperadmin` TINYINT(1) NULL DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `Index 2` (`username`)
)ENGINE=INNODB, DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS whale.`user_action` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(100) NULL,
	`useraction` VARCHAR(500) NULL DEFAULT NULL,
	`action_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)ENGINE=INNODB, DEFAULT CHARSET=UTF8;